[[image_sensor]]
id = 101
name = "IMX477"
manufacturer = "Sony"
part_number = "IMX477"
pixel_size_x = 1.55
pixel_size_y = 1.55
pixels_x = 4056
pixels_y = 3040

[[image_sensor]]
id = 102
name = "IMX678"
manufacturer = "Sony"
part_number = "IMX678"
pixel_size_x = 2.0
pixel_size_y = 2.0
pixels_x = 3840
pixels_y = 2160

[[image_sensor]]
id = 3
name = "IMX900"
manufacturer = "Sony"
part_number = "IMX900"
pixel_size_x = 3.2
pixel_size_y = 3.2
pixels_x = 2048
pixels_y = 2048
