[[image_sensor]]
id = "101"
name = "Sony IMX296LQR-C"
manufacturer = "Sony"
part_number = "IMX296LQR-C"
pixel_size_x = 3.45
pixel_size_y = 3.45
pixels_x = 1456
pixels_y = 1088

[[image_sensor]]
id = "102"
name = "IMX678"
manufacturer = "Sony"
part_number = "IMX678"
pixel_size_x = 2.0
pixel_size_y = 2.0
pixels_x = 3840
pixels_y = 2160

