[device]
id = 1
name = "Bench-Unit-1"
serial_number = "2025-12345"
encryption_key = "${DEVICE_ENCRYPTION_KEY}"

image_sensor_id = 101
source_optics_id = 201
detect_optics_id = 301
io_hardware_id = 401
